### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by maint14** [lukadriel7/nestjs-rabbitmq-transporter#5]
Hello @lukadriel7 !

First of all, I would like to congratulate you on this package, it has been very helpful for me in managing exchange rabbits.

I would like to ask you, since I noticed a small bug on context management and in the routingKey '*', the possibility to commit on a separate branch this management, since I should have been able to fix these two things

what do you think?

**Comment by lukadriel7** [comment]
Hello @maint14 ,
Sure go ahead and make a pull request. Help is always welcome

**Comment by maint14** [comment]
Thanks @lukadriel7 for the fast response.

I'm not so pratical with open source and i'm not able to push separate branch on your repository for creating a PR.

Can you explain me how i can do it?
Maybe some repository settings are wrong for this case?

**Comment by lukadriel7** [comment]
Okay, I'll try to guide you.

- First, you create a fork of my repository
- Then you create a branch of your fork where you do your changes
- After the changes are complete, just go back to your fork on github, select `Pull requests` and click the button `New pull request`
- You will be able to see my repository as the base repository, and yours as the head repository
- Select the branch you worked on and create the pull request

**Comment by maint14** [comment]
Thank you very much.

I'll do in few minutes

**Comment by maint14** [comment]
Done. Waiting for your review. 

Thank you so much
